# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: google-auth-sidecar
build:
  googleCloudBuild:
    projectId: project-id
  artifacts:
  - image: gcr.io/project-id/google-auth-sidecar
deploy:
  kubectl:
    flags:
      global: ["--namespace=apps"]
    manifests:
    - google-auth-sidecar.yaml
