## k create configmap tracking-proto -n apps --from-file=service.pb

apiVersion: apps/v1
kind: Deployment
metadata:
 name: tracking
spec:
 selector:
   matchLabels:
     app: tracking 
 template:
   metadata:
     annotations:
       readiness.status.sidecar.istio.io/applicationPorts: '50051'
       readiness.status.sidecar.istio.io/initialDelaySeconds: '20'
       sidecar.istio.io/userVolume: '[{"name": "tracking-proto","configMap": {"defaultMode": 420,"name": "tracking-proto"}}]'
       sidecar.istio.io/userVolumeMount: '[{"name": "tracking-proto", "mountPath": "/proto", "readonly": true}]'
     labels:
       app: tracking
       version: v1
       managed-by: apigee
   spec:
     serviceAccountName: apps
     containers:
     - image: tracking
       imagePullPolicy: IfNotPresent
       name: tracking
       ports:
       - containerPort: 50051
       volumeMounts:
         - mountPath: /etc/secret
           name: svc-account-volume
           readOnly: true 
     volumes:
     - name: svc-account-volume
       secret:
         defaultMode: 420
         secretName: google-auth-svc-account
         optional: true
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tracking-transcode
  namespace: apps
spec:
  workloadSelector:
    labels:
      app: tracking
  configPatches:

  - applyTo: HTTP_FILTER
    match:
      #proxy:
      #  proxyVersion: '^1\.(8|1\d).*'
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router

    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.grpc_json_transcoder
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
          proto_descriptor: "/proto/service.pb"
          services: ["sample_apps.v1.Shipment"]
          print_options:
            add_whitespace: true
            always_print_primitive_fields: true
            always_print_enums_as_ints: false
            preserve_proto_field_names: false
