// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package sample_apps_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//GetTrackingRequest set a tracking identifier
type GetTrackingRequest struct {
	//tracking_id is the identifier for tracking
	TrackingId           string   `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTrackingRequest) Reset()         { *m = GetTrackingRequest{} }
func (m *GetTrackingRequest) String() string { return proto.CompactTextString(m) }
func (*GetTrackingRequest) ProtoMessage()    {}
func (*GetTrackingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *GetTrackingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrackingRequest.Unmarshal(m, b)
}
func (m *GetTrackingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrackingRequest.Marshal(b, m, deterministic)
}
func (m *GetTrackingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrackingRequest.Merge(m, src)
}
func (m *GetTrackingRequest) XXX_Size() int {
	return xxx_messageInfo_GetTrackingRequest.Size(m)
}
func (m *GetTrackingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrackingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrackingRequest proto.InternalMessageInfo

func (m *GetTrackingRequest) GetTrackingId() string {
	if m != nil {
		return m.TrackingId
	}
	return ""
}

//Tracking contains information about a shipment
type Tracking struct {
	//tracking_id is the identifier for tracking
	TrackingId string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	//status provides the current status of the shipment
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	//created_time is when the tracking resource was created
	CreateTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	//signed is populated when the shipment is delivered
	Signed string `protobuf:"bytes,5,opt,name=signed,proto3" json:"signed,omitempty"`
	//updated_time is when the resource was last updated
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	//weight of the shipment
	Weight string `protobuf:"bytes,6,opt,name=weight,proto3" json:"weight,omitempty"`
	//est_delivery_date estimated delivery time for shipment
	EstDeliveryTime *timestamp.Timestamp `protobuf:"bytes,7,opt,name=est_delivery_time,json=estDeliveryTime,proto3" json:"est_delivery_time,omitempty"`
	//carrier of the shipmemt
	Carrier              string   `protobuf:"bytes,8,opt,name=carrier,proto3" json:"carrier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracking) Reset()         { *m = Tracking{} }
func (m *Tracking) String() string { return proto.CompactTextString(m) }
func (*Tracking) ProtoMessage()    {}
func (*Tracking) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Tracking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracking.Unmarshal(m, b)
}
func (m *Tracking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracking.Marshal(b, m, deterministic)
}
func (m *Tracking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracking.Merge(m, src)
}
func (m *Tracking) XXX_Size() int {
	return xxx_messageInfo_Tracking.Size(m)
}
func (m *Tracking) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracking.DiscardUnknown(m)
}

var xxx_messageInfo_Tracking proto.InternalMessageInfo

func (m *Tracking) GetTrackingId() string {
	if m != nil {
		return m.TrackingId
	}
	return ""
}

func (m *Tracking) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Tracking) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Tracking) GetSigned() string {
	if m != nil {
		return m.Signed
	}
	return ""
}

func (m *Tracking) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Tracking) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *Tracking) GetEstDeliveryTime() *timestamp.Timestamp {
	if m != nil {
		return m.EstDeliveryTime
	}
	return nil
}

func (m *Tracking) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

//ListTrackingResponse contains a list of tracking information
type ListTrackingResponse struct {
	//trackings contains a repeated list of tracking information
	Trackings []*Tracking `protobuf:"bytes,1,rep,name=trackings,proto3" json:"trackings,omitempty"`
	//next_page_token is used for pagination
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTrackingResponse) Reset()         { *m = ListTrackingResponse{} }
func (m *ListTrackingResponse) String() string { return proto.CompactTextString(m) }
func (*ListTrackingResponse) ProtoMessage()    {}
func (*ListTrackingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ListTrackingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTrackingResponse.Unmarshal(m, b)
}
func (m *ListTrackingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTrackingResponse.Marshal(b, m, deterministic)
}
func (m *ListTrackingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTrackingResponse.Merge(m, src)
}
func (m *ListTrackingResponse) XXX_Size() int {
	return xxx_messageInfo_ListTrackingResponse.Size(m)
}
func (m *ListTrackingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTrackingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTrackingResponse proto.InternalMessageInfo

func (m *ListTrackingResponse) GetTrackings() []*Tracking {
	if m != nil {
		return m.Trackings
	}
	return nil
}

func (m *ListTrackingResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTrackingRequest)(nil), "sample_apps.v1.GetTrackingRequest")
	proto.RegisterType((*Tracking)(nil), "sample_apps.v1.Tracking")
	proto.RegisterType((*ListTrackingResponse)(nil), "sample_apps.v1.ListTrackingResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0x16, 0xd2, 0x74, 0x9c, 0xb6, 0x62, 0x55, 0x55, 0x2b, 0x53, 0xa9, 0x91, 0x55,
	0xa1, 0x9c, 0x6c, 0x35, 0x08, 0x2e, 0xdc, 0x2a, 0x3e, 0x84, 0xc4, 0x21, 0x4a, 0x73, 0xb7, 0x36,
	0xf6, 0xe0, 0xae, 0x1a, 0xef, 0x2e, 0xde, 0x89, 0xa1, 0x42, 0x5c, 0x78, 0x05, 0x1e, 0x8c, 0x03,
	0x0f, 0xc0, 0x85, 0x07, 0x41, 0xf6, 0xda, 0xc5, 0xa4, 0xa0, 0x1c, 0xe7, 0xeb, 0xf7, 0xff, 0x7b,
	0x3c, 0x0b, 0x07, 0x16, 0xcb, 0x4a, 0xa6, 0x18, 0x99, 0x52, 0x93, 0x66, 0x87, 0x56, 0x14, 0x66,
	0x85, 0x89, 0x30, 0xc6, 0x46, 0xd5, 0x45, 0xf0, 0x38, 0xd7, 0x3a, 0x5f, 0x61, 0xdc, 0x54, 0x97,
	0xeb, 0xf7, 0x31, 0x16, 0x86, 0x6e, 0x5d, 0x73, 0x70, 0xda, 0x16, 0x85, 0x91, 0xb1, 0x50, 0x4a,
	0x93, 0x20, 0xa9, 0x95, 0x6d, 0xab, 0x67, 0x9b, 0xa3, 0x24, 0x0b, 0xb4, 0x24, 0x0a, 0xe3, 0x1a,
	0xc2, 0x67, 0xc0, 0xde, 0x20, 0x2d, 0x4a, 0x91, 0xde, 0x48, 0x95, 0xcf, 0xf1, 0xc3, 0x1a, 0x2d,
	0xb1, 0x33, 0xf0, 0xa9, 0x4d, 0x25, 0x32, 0xe3, 0xde, 0xd8, 0x9b, 0xec, 0xcf, 0xa1, 0x4b, 0xbd,
	0xcd, 0xc2, 0xef, 0x3b, 0x30, 0xec, 0x86, 0xb6, 0x76, 0xb3, 0x13, 0x18, 0x58, 0x12, 0xb4, 0xb6,
	0x7c, 0xa7, 0xa9, 0xb5, 0x11, 0x7b, 0x01, 0x7e, 0x5a, 0xa2, 0x20, 0x4c, 0x6a, 0x5b, 0x7c, 0x77,
	0xec, 0x4d, 0xfc, 0x69, 0x10, 0x39, 0xcf, 0x51, 0xe7, 0x39, 0x5a, 0x74, 0x9e, 0xe7, 0xe0, 0xda,
	0xeb, 0x44, 0x03, 0x95, 0xb9, 0xc2, 0x8c, 0x3f, 0x6c, 0xa1, 0x4d, 0x54, 0x43, 0xd7, 0x26, 0xbb,
	0x83, 0x3e, 0xd8, 0x0e, 0x75, 0xed, 0x1d, 0xf4, 0x23, 0xca, 0xfc, 0x9a, 0xf8, 0xc0, 0x41, 0x5d,
	0xc4, 0x5e, 0xc3, 0x23, 0xb4, 0x94, 0x64, 0xb8, 0x92, 0x15, 0x96, 0xb7, 0x0e, 0xbd, 0xb7, 0x15,
	0x7d, 0x84, 0x96, 0x5e, 0xb6, 0x33, 0x0d, 0x9f, 0xc3, 0x5e, 0x2a, 0xca, 0x52, 0x62, 0xc9, 0x87,
	0x8d, 0x40, 0x17, 0x86, 0x15, 0x1c, 0xbf, 0x93, 0xb6, 0xf7, 0x27, 0xac, 0xd1, 0xca, 0x22, 0x7b,
	0x0e, 0xfb, 0xdd, 0x26, 0x2d, 0xf7, 0xc6, 0xbb, 0x13, 0x7f, 0xca, 0xa3, 0xbf, 0x0f, 0x24, 0xba,
	0x1b, 0xfa, 0xd3, 0xca, 0x9e, 0xc0, 0x91, 0xc2, 0x4f, 0x94, 0x18, 0x91, 0x63, 0x42, 0xfa, 0x06,
	0x55, 0xbb, 0xfc, 0x83, 0x3a, 0x3d, 0x13, 0x39, 0x2e, 0xea, 0xe4, 0xf4, 0xa7, 0x07, 0xc3, 0xab,
	0x6b, 0x69, 0x0a, 0x54, 0xc4, 0x34, 0xf8, 0xbd, 0x6b, 0x60, 0xe1, 0xa6, 0xd0, 0xfd, 0x53, 0x09,
	0xfe, 0x6b, 0x26, 0x0c, 0xbf, 0xfe, 0xf8, 0xf5, 0x6d, 0xe7, 0x94, 0x05, 0x71, 0x75, 0x11, 0x77,
	0xc6, 0xe2, 0xcf, 0xbd, 0x53, 0xf9, 0xc2, 0x96, 0x30, 0xea, 0x7f, 0x35, 0x3b, 0xb9, 0xb7, 0xcc,
	0x57, 0xf5, 0xad, 0x07, 0xe7, 0x9b, 0x2a, 0xff, 0xda, 0x55, 0x78, 0xdc, 0x28, 0x1e, 0xb2, 0x51,
	0x5f, 0xf1, 0xf2, 0x1c, 0x58, 0xaa, 0x8b, 0x0d, 0xc0, 0xe5, 0xe8, 0xca, 0xbd, 0xb9, 0x59, 0x2d,
	0x34, 0xf3, 0x96, 0x83, 0x46, 0xf1, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x51, 0x11,
	0x2b, 0x8c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShipmentClient is the client API for Shipment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShipmentClient interface {
	//GetTracking gets a specific tracking identifier
	GetTracking(ctx context.Context, in *GetTrackingRequest, opts ...grpc.CallOption) (*Tracking, error)
	//ListTracking lists all the tracking objects
	ListTracking(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListTrackingResponse, error)
}

type shipmentClient struct {
	cc *grpc.ClientConn
}

func NewShipmentClient(cc *grpc.ClientConn) ShipmentClient {
	return &shipmentClient{cc}
}

func (c *shipmentClient) GetTracking(ctx context.Context, in *GetTrackingRequest, opts ...grpc.CallOption) (*Tracking, error) {
	out := new(Tracking)
	err := c.cc.Invoke(ctx, "/sample_apps.v1.Shipment/GetTracking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentClient) ListTracking(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListTrackingResponse, error) {
	out := new(ListTrackingResponse)
	err := c.cc.Invoke(ctx, "/sample_apps.v1.Shipment/ListTracking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShipmentServer is the server API for Shipment service.
type ShipmentServer interface {
	//GetTracking gets a specific tracking identifier
	GetTracking(context.Context, *GetTrackingRequest) (*Tracking, error)
	//ListTracking lists all the tracking objects
	ListTracking(context.Context, *empty.Empty) (*ListTrackingResponse, error)
}

// UnimplementedShipmentServer can be embedded to have forward compatible implementations.
type UnimplementedShipmentServer struct {
}

func (*UnimplementedShipmentServer) GetTracking(ctx context.Context, req *GetTrackingRequest) (*Tracking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTracking not implemented")
}
func (*UnimplementedShipmentServer) ListTracking(ctx context.Context, req *empty.Empty) (*ListTrackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTracking not implemented")
}

func RegisterShipmentServer(s *grpc.Server, srv ShipmentServer) {
	s.RegisterService(&_Shipment_serviceDesc, srv)
}

func _Shipment_GetTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentServer).GetTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_apps.v1.Shipment/GetTracking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentServer).GetTracking(ctx, req.(*GetTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shipment_ListTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentServer).ListTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_apps.v1.Shipment/ListTracking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentServer).ListTracking(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shipment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sample_apps.v1.Shipment",
	HandlerType: (*ShipmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTracking",
			Handler:    _Shipment_GetTracking_Handler,
		},
		{
			MethodName: "ListTracking",
			Handler:    _Shipment_ListTracking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
