// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Inventory struct {
	SalePrice            *Price  `json:"salePrice"`
	SellOnGoogleQuantity *string `json:"sellOnGoogleQuantity"`
	Availability         *int    `json:"availability"`
	Kind                 *string `json:"kind"`
	Price                *Price  `json:"price"`
}

type Item struct {
	Inventory *Inventory `json:"inventory"`
	ProductID *string    `json:"productId"`
	StoreCode *string    `json:"storeCode"`
}

type LineItem struct {
	Item     *Item `json:"item"`
	Quantity *int  `json:"quantity"`
}

type Order struct {
	OperationID string      `json:"operationId"`
	ShipmentID  *string     `json:"shipmentId"`
	LineItems   []*LineItem `json:"lineItems"`
	Carrier     *string     `json:"carrier"`
	TrackingID  *string     `json:"trackingId"`
}

type Price struct {
	Currency *string `json:"currency"`
	Value    *string `json:"value"`
}
